[project]
name = "vite-fastapi-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jc", email = "107809331+y3eet@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "argon2-cffi>=25.1.0",
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.13.0",
    "sqlmodel>=0.0.42",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
vite-fastapi-template = "vite_fastapi_template:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.6",
]
