"""add user fuzzy search

Revision ID: 32ed2e05b20f
Revises: 669d6586dc50
Create Date: 2026-09-08 10:49:15.110534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "32ed2e05b20f"
down_revision: Union[str, Sequence[str], None] = "669d6586dc50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.add_column("users", sa.Column("blocked", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "is_active")
    op.drop_column("users", "full_name")

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.execute(
        'CREATE INDEX ix_user_username_trgm ON "users" USING gin (username gin_trgm_ops)'
    )
    op.execute(
        'CREATE INDEX ix_user_email_trgm ON "users" USING gin (email gin_trgm_ops)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "updated_at")
    op.drop_column("users", "blocked")
    op.drop_column("users", "username")

    op.execute("DROP INDEX IF EXISTS ix_user_email_trgm")
    op.execute("DROP INDEX IF EXISTS ix_user_username_trgm")

    # Only drop the extension if nothing else in your schema depends on it
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
